### ISSUE TITLE
DeprecationWarning: TextChannel#sendMessage: use TextChannel#send instead

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/Discord-Bot#12]
(node:15) DeprecationWarning: TextChannel#sendMessage: use TextChannel#send instead

**Comment by Keegangrajek** [comment]
if you change the code to `send("whatever");` instead of `sendMessage("whatever");` you shouldn't get this warning in the console. However, this is still a bug and should be fixed.

**Comment by thehonkinggoose** [comment]
Has this issue been resolved yet? If not could I do a PR?

**Comment by RyanTheAllmighty** [comment]
@nsuchy nah not been done yet. a PR would be very welcome :)

**Comment by thehonkinggoose** [comment]
@RyanTheAllmighty Awesome, so to confirm what I'm doing I will change all `sendMessage("whatever");` commands in the code to `send("whatever");`? I can probably have a PR ready by sometime tomorrow, I have to check what I have planned. Let me know :)

**Comment by RyanTheAllmighty** [comment]
@nsuchy looks like that's the case according to https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=send

**Comment by thehonkinggoose** [comment]
I'm not seeing `sendMessage(` anywhere when I search the code, should this issue be closed?

**Comment by RyanTheAllmighty** [comment]
Oh yeah looks like I did it as part of commit c80802a4d1bf7f862850cf18df6fb83a57b0d05d

Sorry for wasting your time :) I'll close it now

**Comment by thehonkinggoose** [comment]
@RyanTheAllmighty No worries, let me know if there's anything else I can help with. Always happy to contribute to open source stuff in what-ever way I can :)
