### ISSUE TITLE
crash when starting in either dev or production

### ISSUE THREAD

**Issue by Aaronstar-McClure** [ATLauncher/Discord-Bot#13]
[nodemon] starting `atlauncher-scripts babel-run src`
Running 'node F:\Discord-Bot/node_modules/.bin/babel-node F:\Discord-Bot\src --p
resets=@atlauncher/babel-preset-atlauncher'

F:\Discord-Bot\node_modules\.bin\babel-node:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
[nodemon] app crashed - waiting for file changes before starting...

**Comment by RyanTheAllmighty** [comment]
If you wish to run in production mode please consider using the Docker image (https://hub.docker.com/r/atlauncher/discord-bot/)

Please provide the output to the following commands:

`node -v`
`npm -v`

**Comment by Aaronstar-McClure** [comment]
F:\Discord-Bot>node -v
v8.5.0

F:\Discord-Bot>npm -v
5.3.0


   ?─────────────────────────────────────?
   │                                     │
   │   Update available 5.3.0 → 5.4.2    │
   │     Run npm i -g npm to update      │
   │                                     │
   ?─────────────────────────────────────?



i will update npm and see if it gets fixed

**Comment by Aaronstar-McClure** [comment]
F:\Discord-Bot>npm run build

> @atlauncher/discord-bot@0.1.0 build F:\Discord-Bot
> atlauncher-scripts build

Running 'node F:\Discord-Bot/node_modules/.bin/babel F:\Discord-Bot\src --copy-f
iles --out-dir F:\Discord-Bot\dist --presets=@atlauncher/babel-preset-atlauncher
'

F:\Discord-Bot\node_modules\.bin\babel:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @atlauncher/discord-bot@0.1.0 build: `atlauncher-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @atlauncher/discord-bot@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*user*\AppData\Roaming\npm-cache\_logs\2017-09-23T15_0
7_36_630Z-debug.log

F:\Discord-Bot>

**Comment by Aaronstar-McClure** [comment]
Also, i assume if the bot is built on windows, it can be run on linux? I cant use dockers on my server.

**Comment by RyanTheAllmighty** [comment]
The code and docker containers are cross platform, so doesn't matter where it's built and/or run

**Comment by RyanTheAllmighty** [comment]
Building works fine for me on a fresh install on OSX and Node 8.4.0/NPM 5.3.0.

I'll take a look on my Windows machine

**Comment by Aaronstar-McClure** [comment]
Ill try redownloading from github and doing the install and build again

**Comment by Aaronstar-McClure** [comment]
i deleted the github clone, redownloaded it, ran npm install, and npm run build. errored with syntax error.
F:\Discord-Bot>npm -v
5.4.2

F:\Discord-Bot>node -v
v8.5.0

**Comment by Aaronstar-McClure** [comment]
is there a way for me to simply download a non-dockered, fully built install?

**Comment by RyanTheAllmighty** [comment]
There is not sorry.

**Comment by Aaronstar-McClure** [comment]
strange...
linux ubuntu, 
npm 5.3.0
node 8.4.0
build worked. maby it is a windows thing?

**Comment by RyanTheAllmighty** [comment]
Issue fixed. Pull down latest changes to fix issues with Windows
