### ISSUE TITLE
bot crashes every time someone speaks

### ISSUE THREAD

**Issue by Aaronstar-McClure** [ATLauncher/Discord-Bot#15]
ATBotcb9-6b0d-45
> @atlauncher/discord-bot@0.1.0 start /var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be
> node dist
 
I am ready!
uncaughtException TypeError: Cannot read property 'users' of undefined
    at PollWatcher.shouldRun (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/dist/BaseModule.js:133:40)
    at watchers.(anonymous function).forEach.watcher (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/dist/WatcherBus.js:100:33)
    at Array.forEach (<anonymous>)
    at Client.bot.on.args (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/dist/WatcherBus.js:99:39)
    at emitOne (events.js:120:20)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:325:35)
    at WebSocketConnection.onMessage (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:288:17)
uncaughtException { Error: RSV2 and RSV3 must be clear
    at Receiver.getInfo (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/ws/lib/Receiver.js:184:18)
    at Receiver.startLoop (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/ws/lib/Receiver.js:153:16)
    at Receiver.add (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:587:20)
  type: 'error',
  target: 
   WebSocket {
     domain: null,
     _events: 
      { message: [Object],
        open: [Object],
        error: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 2,
     bytesReceived: 3620,
     extensions: {},
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: { [Function: bound finalize] __ultron: 0 },
     _finalizeCalled: false,
     _closeMessage: null,
     _closeTimer: null,
     _closeCode: null,
     _receiver: 
      Receiver {
        binaryType: 'nodebuffer',
        extensions: {},
        maxPayload: 0,
        bufferedBytes: 145,
        buffers: [Array],
        compressed: false,
        payloadLength: 465,
        fragmented: 0,
        masked: false,
        fin: true,
        mask: null,
        opcode: 1,
        totalPayloadLength: 0,
        messageLength: 0,
        fragments: [],
        cleanupCallback: null,
        hadError: false,
        dead: false,
        loop: true,
        onmessage: [Function],
        onclose: [Function],
        onerror: [Function],
        onping: [Function],
        onpong: [Function],
        state: 0 },
     _sender: 
      Sender {
        perMessageDeflate: undefined,
        _socket: [Object],
        firstFragment: true,
        compress: false,
        bufferedBytes: 0,
        deflating: false,
        queue: [],
        onerror: [Function] },
     _socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'gateway.discord.gg',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 709,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 688,
        [Symbol(bytesRead)]: 0 },
     _ultron: Ultron { id: 0, ee: [Object] },
     protocolVersion: 13,
     _isServer: false,
     url: 'wss://gateway.discord.gg/?v=6&encoding=json',
     _req: null } }
uncaughtException { Error: RSV1 must be clear
    at Receiver.getInfo (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/ws/lib/Receiver.js:191:18)
    at Receiver.startLoop (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/ws/lib/Receiver.js:153:16)
    at Receiver.add (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:587:20)
  type: 'error',
  target: 
   WebSocket {
     domain: null,
     _events: 
      { message: [Object],
        open: [Object],
        error: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 2,
     bytesReceived: 3624,
     extensions: {},
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: { [Function: bound finalize] __ultron: 0 },
     _finalizeCalled: false,
     _closeMessage: null,
     _closeTimer: 
      Timeout {
        _called: false,
        _idleTimeout: 30000,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 391052,
        _onTimeout: [Object],
        _timerArgs: [Array],
        _repeat: null,
        _destroyed: false,
        [Symbol(asyncId)]: 783,
        [Symbol(triggerAsyncId)]: 779 },
     _closeCode: null,
     _receiver: 
      Receiver {
        binaryType: 'nodebuffer',
        extensions: {},
        maxPayload: 0,
        bufferedBytes: 147,
        buffers: [Array],
        compressed: false,
        payloadLength: 465,
        fragmented: 0,
        masked: false,
        fin: true,
        mask: null,
        opcode: 1,
        totalPayloadLength: 0,
        messageLength: 0,
        fragments: [],
        cleanupCallback: null,
        hadError: false,
        dead: false,
        loop: true,
        onmessage: [Function],
        onclose: [Function],
        onerror: [Function],
        onping: [Function],
        onpong: [Function],
        state: 0 },
     _sender: 
      Sender {
        perMessageDeflate: undefined,
        _socket: [Object],
        firstFragment: true,
        compress: false,
        bufferedBytes: 0,
        deflating: false,
        queue: [],
        onerror: [Function] },
     _socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'gateway.discord.gg',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 709,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 688,
        [Symbol(bytesRead)]: 0 },
     _ultron: Ultron { id: 0, ee: [Object] },
     protocolVersion: 13,
     _isServer: false,
     url: 'wss://gateway.discord.gg/?v=6&encoding=json',
     _req: null } }

Also, what is the command to shut down the bot from console? I cant find it in any documentation.

**Comment by Aaronstar-McClure** [comment]
note that is supposed to be (colon)100(colon)33

**Comment by RyanTheAllmighty** [comment]
What's all this pufferd stuff? Might be the cause?

Also there is no shutdown command, just Ctrl+C it

**Comment by Aaronstar-McClure** [comment]
puffered is a free web panel that runs the bot

**Comment by Aaronstar-McClure** [comment]
or rather, puffered is the daemon, for the web panel

**Comment by Aaronstar-McClure** [comment]
wait, i just realised there was more error stuff... i added it

**Comment by RyanTheAllmighty** [comment]
Take a look at my config.json.

The example may be out of date, so look at what you may be missing:

```
{
    "moderator_channel": "moderation-logs",
    "support_channel": "support",
    "rules_channel": "rules",
    "bot_testing_channel": "bot-testing",
    "non_support_channels": [
        "general",
        "general-chat",
        "minecraft",
        "gaming",
        "entertainment",
        "atlauncher-next",
        "development",
        "website-support",
        "introductions"
    ],
    "moderated_channels": [
        "general",
        "general-chat",
        "minecraft",
        "gaming",
        "entertainment",
        "atlauncher-next",
        "development",
        "website-support",
        "introductions",
        "support",
        "bot-testing"
    ],
    "appeal_url": "https://atl.pw/discord-ban-appeal",
    "bypass": {
        "roles": [
            "ATLauncher Staff",
            "NodeCraft Staff",
            "Moderators",
            "AllmightyBot"
        ],
        "users": []
    },
    "bad_words": [
        "bum",
        "hole"
    ],
    "client_id": "",
    "client_secret": "",
    "client_token": ""
}
```

**Comment by Aaronstar-McClure** [comment]
Yes, definantly out of date, thankyou
