### ISSUE TITLE
random crash. bot is running in screen

### ISSUE THREAD

**Issue by Aaronstar-McClure** [ATLauncher/Discord-Bot#17]
root@Darks_server:~/Aaronstar# npm run start

> @atlauncher/discord-bot@0.1.0 start /root/Aaronstar
> node dist

I am ready!
uncaughtException { Error: unexpected server response (520)
    at ClientRequest._req.on (/root/Aaronstar/node_modules/ws/lib/WebSocket.js:650:26)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
  type: 'error',
  target:
   WebSocket {
     domain: null,
     _events:
      { message: [Object],
        open: [Object],
        error: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 0,
     bytesReceived: 0,
     extensions: {},
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: [Function: bound finalize],
     _finalizeCalled: false,
     _closeMessage: null,
     _closeTimer: null,
     _closeCode: null,
     _receiver: null,
     _sender: null,
     _socket: null,
     _ultron: null,
     protocolVersion: 13,
     _isServer: false,
     url: 'wss://gateway.discord.gg/?v=6&encoding=json',
     _req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /?v=6&encoding=json HTTP/1.1\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: BZHl6u3/BA7/Z/mh1b9o9w==\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\nHost: gateway.discord.gg\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/?v=6&encoding=json',
        _ended: false,
        res: [Object],
        aborted: 1517906970745,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: [Object],
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] } } }
root@Darks_server:~/Aaronstar#

**Comment by RyanTheAllmighty** [comment]
The README contains instructions on how to add configs to the Docker image:

https://github.com/ATLauncher/discord-bot#including-config

The errror indicates a server error from Discord of an unknown kind (Error Code 520).
